name: binder_example
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bokeh=1.4.0
  - branca=0.3.1
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - cryptography=2.8
  - cycler=0.10.0
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - folium=0.10.1
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gmp=6.1.2
  - gpxpy=1.4.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.8
  - importlib_metadata=1.3.0
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.2
  - jinja2=2.10.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.0.2
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - packaging=20.0
  - pandas=0.25.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.2
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=19.3.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.2
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.5.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.15.6
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyyaml=5.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.6.0
  - readline=7.0
  - requests=2.22.0
  - scipy=1.3.2
  - send2trash=1.5.0
  - setuptools=44.0.0
  - sip=4.19.8
  - six=1.13.0
  - sqlite=3.30.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.3
  - urllib3=1.25.7
  - vincent=0.4.4
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7

